import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NotificationContainer from "@/1shared/notification/NotificationContainer";
import { CartProvider } from "@/2entities/cart";
import { UserProvider } from "@/2entities/user";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${inter.variable}`}>
        <NotificationContainer />
        <UserProvider>
          <CartProvider>{children}</CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
